name: Build and deploy structurizr site

on:
  push:
    branches:
      - main
      - develop
      - "feature/github-actions"
      - "release/*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate Structurizr site
        run: |
          docker run --rm \
            -v "${{ github.workspace }}:/var/model" \
            ghcr.io/avisi-cloud/structurizr-site-generatr:latest \
            generate-site \
              --git-url https://github.com/${{ github.repository }}.git \
              --workspace-file workspace.dsl \
              --branches main,develop,${GITHUB_REF_NAME} \
              --default-branch main \
              --output-dir /var/model/site

      - name: Upload site artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./site

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3

